spring.application.name=interview-prep

spring.datasource.url=jdbc:postgresql://dpg-d7rp3vu7r5hc739hgf8g-a.singapore-postgres.render.com:5432/prepyan_db
spring.datasource.username=prepyan_db_user
spring.datasource.password=whwmwrFbobWuHS6mrpI8Y7Wz2GTbV5aP

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

groq.api.key=${GROQ_API_KEY}



# \uD83D\uDD25 DB Pool (VERY IMPORTANT - prevents hang)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# \uD83D\uDD25 Performance safety
server.tomcat.max-threads=50
server.tomcat.accept-count=20

# \uD83D\uDD25 Logging (optional)
logging.level.org.springframework.web=INFO