spring.application.name=interview-prep

# DATABASE
spring.datasource.url=jdbc:postgresql://dpg-d7rp3vu7r5hc739hgf8g-a.singapore-postgres.render.com:5432/prepyan_db?sslmode=require
spring.datasource.username=prepyan_db_user
spring.datasource.password=whwmwrFbobWuHS6mrpI8Y7Wz2GTbV5aP
spring.datasource.driver-class-name=org.postgresql.Driver

# HIKARI
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=3000

# JPA
spring.jpa.hibernate.ddl-auto=none

# SERVER
server.port=8080

# GROQ
groq.api.key=${GROQ_API_KEY}

# LOG
logging.level.root=INFO